name: Labeller

on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  label:
    if: contains(github.event.repository.owner, ['puppetlabs', 'puppet-toy-chest'])
    uses: "h0tw1r3/cat-github-actions/.github/workflows/labeller.yml@forked-modules"
