name: "mend"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  mend:
    uses: "h0tw1r3/cat-github-actions/.github/workflows/mend_ruby.yml@forked-modules"
    secrets: "inherit"
