name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Spec:
    uses: "h0tw1r3/cat-github-actions/.github/workflows/module_ci.yml@forked-modules"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "h0tw1r3/cat-github-actions/.github/workflows/module_acceptance.yml@forked-modules"
    secrets: "inherit"
